### ISSUE TITLE
Go back to Android only

### ISSUE THREAD

**Issue by educandian** [ProjectValhalla/OdinMultiBootGuides#29]
I did the windows installation in Odin and everything went normally. But when I did the restore for Android only, the floating icons (when you swipe screen from the right) is not working. What to do?

**Comment by dfilskov** [comment]
Do you have a solution that others reading this could use?

**Comment by educandian** [comment]
I did the process on the [AYN website](https://www.ayntec.com/pages/software) and it worked again.
